name: CI pipeline

on:
  push:
    branches: [main]

jobs:
  sonar:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: SonarQube scan
        shell: powershell
        run: |
          sonar-scanner.bat `
            -D"sonar.projectKey=NodeJsApp" `
            -D"sonar.sources=." `
            -D"sonar.host.url=$env:SONAR_HOST_URL" `
            -D"sonar.login=$env:SONAR_TOKEN"
        env:
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
