name: SonarQube Scan

on: workflow_dispatch

jobs:
  sonar:
    runs-on: [self-hosted,Linux]

    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: SonarQube analysis
        uses: SonarSource/sonarqube-scan-action@v6
        with:
          args: >
            -Dsonar.projectKey=NodeJs.App1
            -Dsonar.sources=.
            -Dsonar.qualitygate.wait=true
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
